apiVersion: v1
kind: ResourceQuota
metadata: # kpt-merge: tenant-name/quota
  name: quota
  namespace: project-a
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 6Gi
    persistentvolumeclaims: "5"
    requests.storage: 10Gi
