apiVersion: fn.kpt.dev/v1alpha1
kind: StarlarkRun
metadata: # kpt-merge: /ns-invariant
  name: ns-invariant
source: "def ensure_one_namespace(resource_list):\n  num_ns = 0\n  for resource in resource_list[\"items\"]:\n    if resource[\"apiVersion\"] == \"v1\" and resource[\"kind\"] == \"Namespace\":\n      num_ns += 1\n  # only one namespace is allowed\n  if num_ns > 1:\n    fail(\"pkg must contain single namespace\") \n\nensure_one_namespace(ctx.resource_list)"
